"""baseline matching v1.0-flask schema (parity-fixed)

Revision ID: 34b9481e6509
Revises: 
Create Date: 2026-05-09 03:14:56.256432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.core.database import JSONText

# revision identifiers, used by Alembic.
revision: str = '34b9481e6509'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('status', sa.Text(), server_default='backlog', nullable=False),
    sa.Column('priority', sa.Text(), server_default='medium', nullable=False),
    sa.Column('type', sa.Text(), server_default='feature', nullable=True),
    sa.Column('tags_json', JSONText(), server_default='[]', nullable=True),
    sa.Column('link', sa.Text(), server_default='', nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_tasks_due_date', 'admin_tasks', ['due_date'], unique=False)
    op.create_index('idx_admin_tasks_priority', 'admin_tasks', ['priority'], unique=False)
    op.create_index('idx_admin_tasks_status', 'admin_tasks', ['status'], unique=False)
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('subscription_plan', sa.Text(), server_default='academy10', nullable=False),
    sa.Column('max_seats', sa.Integer(), server_default='10', nullable=False),
    sa.Column('pooled_storage_gb', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_geo_cache',
    sa.Column('ip', sa.Text(), nullable=False),
    sa.Column('country_code', sa.Text(), nullable=True),
    sa.Column('country_name', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(precision=24), nullable=True),
    sa.Column('lon', sa.Float(precision=24), nullable=True),
    sa.Column('resolved_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('mailing_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('research_url_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('used_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_research_url_log_domain', 'research_url_log', ['domain'], unique=False)
    op.create_index('idx_research_url_log_tier', 'research_url_log', ['tier'], unique=False)
    op.create_index('idx_research_url_log_used_at', 'research_url_log', ['used_at'], unique=False)
    op.create_table('admin_task_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Text(), server_default='admin', nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['admin_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_task_comments_task', 'admin_task_comments', ['task_id', 'created_at'], unique=False)
    op.create_table('admin_task_subtasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('done', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['admin_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_task_subtasks_task', 'admin_task_subtasks', ['task_id', 'position'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), server_default='', nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), server_default='coach', nullable=False),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('email_verified', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.Text(), nullable=True),
    sa.Column('active_team_id', sa.Integer(), nullable=True),
    sa.Column('email_marketing', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('unsubscribe_token', sa.Text(), nullable=True),
    sa.Column('email_infra_signup', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('push_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('push_quiet_start', sa.SmallInteger(), server_default='22', nullable=True),
    sa.Column('push_quiet_end', sa.SmallInteger(), server_default='7', nullable=True),
    sa.Column('last_push_sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.Text(), server_default='Asia/Jerusalem', nullable=True),
    sa.Column('subscription_plan', sa.Text(), server_default='trial', nullable=True),
    sa.Column('trial_ends_at', sa.Text(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('is_club_admin', sa.Integer(), server_default='0', nullable=True),
    sa.Column('data_purge_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_club', 'users', ['club_id'], unique=False)
    op.create_index('idx_users_deleted', 'users', ['deleted_at'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), server_default='', nullable=True),
    sa.Column('details', sa.Text(), server_default='', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_auth_tokens_expires', 'auth_tokens', ['expires_at'], unique=False)
    op.create_index('idx_auth_tokens_user_purpose', 'auth_tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('clip_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('share_token', sa.Text(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('clip_ids', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('timeline_json', JSONText(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('coach_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_language', sa.Text(), server_default='en', nullable=True),
    sa.Column('detail_level', sa.Text(), server_default='medium', nullable=True),
    sa.Column('focus_areas', sa.Text(), server_default='', nullable=True),
    sa.Column('avoid_topics', sa.Text(), server_default='', nullable=True),
    sa.Column('practice_duration', sa.Integer(), server_default='90', nullable=True),
    sa.Column('coaching_style', sa.Text(), server_default='', nullable=True),
    sa.Column('custom_notes', sa.Text(), server_default='', nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_coach_prefs_user', 'coach_preferences', ['user_id'], unique=False)
    op.create_table('compile_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.Text(), nullable=False),
    sa.Column('config_json', JSONText(), server_default='{}', nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sa.Text(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_log_status_date', 'email_log', ['status', 'sent_at'], unique=False)
    op.create_index('idx_email_log_user_template', 'email_log', ['user_id', 'template', 'sent_at'], unique=False)
    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), server_default='pro', nullable=False),
    sa.Column('redeemed_by', sa.Integer(), nullable=True),
    sa.Column('redeemed_at', sa.Text(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_invite_code', 'invite_codes', ['code'], unique=False)
    op.create_table('mailing_list_members',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['mailing_lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('list_id', 'user_id')
    )
    op.create_index('idx_mailing_list_members_user', 'mailing_list_members', ['user_id'], unique=False)
    op.create_table('page_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('page_path', sa.Text(), nullable=False),
    sa.Column('page_section', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), server_default='0', nullable=True),
    sa.Column('entered_at', sa.Text(), nullable=False),
    sa.Column('exited_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pv_date', 'page_views', ['created_at'], unique=False)
    op.create_index('idx_pv_section', 'page_views', ['page_section'], unique=False)
    op.create_index('idx_pv_session', 'page_views', ['session_id'], unique=False)
    op.create_index('idx_pv_user', 'page_views', ['user_id'], unique=False)
    op.create_table('play_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('play_json', JSONText(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('push_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('deep_link', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_push_log_status', 'push_log', ['status', 'sent_at'], unique=False)
    op.create_index('idx_push_log_user_sent', 'push_log', ['user_id', 'sent_at'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index('idx_push_subs_user', 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('device_info', sa.Text(), server_default='', nullable=True),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sales_inquiries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), server_default='', nullable=True),
    sa.Column('num_coaches', sa.Text(), server_default='', nullable=True),
    sa.Column('num_teams', sa.Text(), server_default='', nullable=True),
    sa.Column('current_tools', sa.Text(), server_default='', nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=True),
    sa.Column('status', sa.Text(), server_default='new', nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scouting_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('position', sa.Text(), server_default='', nullable=True),
    sa.Column('dominant_hand', sa.Text(), server_default='', nullable=True),
    sa.Column('team_name', sa.Text(), server_default='', nullable=True),
    sa.Column('team_logo_s3_key', sa.Text(), server_default='', nullable=True),
    sa.Column('photo_s3_key', sa.Text(), server_default='', nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_user_id', sa.Text(), nullable=False),
    sa.Column('provider_email', sa.Text(), nullable=True),
    sa.Column('provider_data', JSONText(), server_default='{}', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_social_provider_user')
    )
    op.create_index('idx_social_provider', 'social_accounts', ['provider', 'provider_user_id'], unique=False)
    op.create_table('team_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.Text(), nullable=False),
    sa.Column('league', sa.Text(), nullable=True),
    sa.Column('division', sa.Text(), nullable=True),
    sa.Column('play_style', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('extra_storage_gb', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('agent_key', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), server_default='0', nullable=True),
    sa.Column('completion_tokens', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=True),
    sa.Column('cost_usd', sa.Float(precision=24), server_default='0', nullable=True),
    sa.Column('endpoint', sa.Text(), server_default='chat', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_usage_date', 'api_usage_logs', ['created_at'], unique=False)
    op.create_index('idx_api_usage_model', 'api_usage_logs', ['model'], unique=False)
    op.create_index('idx_api_usage_user', 'api_usage_logs', ['user_id'], unique=False)
    op.create_table('clip_playlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_used', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_session', 'conversations', ['session_id'], unique=False)
    op.create_index('idx_conversations_team_id', 'conversations', ['team_id'], unique=False)
    op.create_index('idx_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_name', sa.Text(), nullable=False),
    sa.Column('attributes_json', JSONText(), server_default='{}', nullable=True),
    sa.Column('last_mentioned_at', sa.DateTime(), nullable=True),
    sa.Column('mention_count', sa.Integer(), server_default='1', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', 'entity_type', 'entity_name', name='uq_entities_unique')
    )
    op.create_index('idx_entities_user_team', 'entities', ['user_id', 'team_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('agent_key', sa.Text(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('response_content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), server_default='', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_user_agent', 'feedback', ['user_id', 'agent_key'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_session_id', sa.Text(), nullable=True),
    sa.Column('agent_key', sa.Text(), nullable=True),
    sa.Column('importance', sa.Integer(), server_default='5', nullable=True),
    sa.Column('access_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('embedding_json', JSONText(), nullable=True),
    sa.ForeignKeyConstraint(['superseded_by'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memories_category', 'memories', ['user_id', 'category', 'active'], unique=False)
    op.create_index('idx_memories_user_active', 'memories', ['user_id', 'active'], unique=False)
    op.create_index('idx_memories_user_team', 'memories', ['user_id', 'team_id', 'active'], unique=False)
    op.create_table('notebook_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('entry_date', sa.Text(), nullable=False),
    sa.Column('content_json', JSONText(), server_default='{}', nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), server_default='manual', nullable=False),
    sa.Column('tags_json', JSONText(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nb_entries_date', 'notebook_entries', ['team_id', 'entry_date'], unique=False)
    op.create_index('idx_nb_entries_player', 'notebook_entries', ['player_id'], unique=False)
    op.create_index('idx_nb_entries_team_type', 'notebook_entries', ['user_id', 'team_id', 'entry_type'], unique=False)
    op.create_table('onboarding_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', 'event', name='uq_onb_user_team_event')
    )
    op.create_index('idx_onb_user_team', 'onboarding_events', ['user_id', 'team_id'], unique=False)
    op.create_table('player_game_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('notebook_entry_id', sa.Integer(), nullable=True),
    sa.Column('game_date', sa.Text(), nullable=False),
    sa.Column('opponent', sa.Text(), server_default='', nullable=True),
    sa.Column('minutes', sa.Integer(), server_default='0', nullable=True),
    sa.Column('points', sa.Integer(), server_default='0', nullable=True),
    sa.Column('fgm', sa.Integer(), server_default='0', nullable=True),
    sa.Column('fga', sa.Integer(), server_default='0', nullable=True),
    sa.Column('three_pm', sa.Integer(), server_default='0', nullable=True),
    sa.Column('three_pa', sa.Integer(), server_default='0', nullable=True),
    sa.Column('ftm', sa.Integer(), server_default='0', nullable=True),
    sa.Column('fta', sa.Integer(), server_default='0', nullable=True),
    sa.Column('oreb', sa.Integer(), server_default='0', nullable=True),
    sa.Column('dreb', sa.Integer(), server_default='0', nullable=True),
    sa.Column('reb', sa.Integer(), server_default='0', nullable=True),
    sa.Column('ast', sa.Integer(), server_default='0', nullable=True),
    sa.Column('stl', sa.Integer(), server_default='0', nullable=True),
    sa.Column('blk', sa.Integer(), server_default='0', nullable=True),
    sa.Column('turnovers', sa.Integer(), server_default='0', nullable=True),
    sa.Column('pf', sa.Integer(), server_default='0', nullable=True),
    sa.Column('plus_minus', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_date', 'opponent', name='uq_pgs_player_game')
    )
    op.create_index('idx_pgs_entry', 'player_game_stats', ['notebook_entry_id'], unique=False)
    op.create_index('idx_pgs_player', 'player_game_stats', ['player_id', 'game_date'], unique=False)
    op.create_index('idx_pgs_team_game', 'player_game_stats', ['user_id', 'team_id', 'game_date'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('height', sa.Text(), nullable=True),
    sa.Column('weight', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dominant_hand', sa.Text(), server_default='', nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('scout_summary', sa.Text(), nullable=True),
    sa.Column('metrics_filled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_players_team_id', 'players', ['team_id'], unique=False)
    op.create_index('idx_players_user_id', 'players', ['user_id'], unique=False)
    op.create_table('plays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('offense_template', sa.Text(), server_default='empty', nullable=True),
    sa.Column('defense_template', sa.Text(), server_default='none', nullable=True),
    sa.Column('players_json', JSONText(), server_default='[]', nullable=True),
    sa.Column('actions_json', JSONText(), server_default='[]', nullable=True),
    sa.Column('ball_holder_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scouting_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('video_type', sa.Text(), server_default='game', nullable=True),
    sa.Column('s3_key', sa.Text(), nullable=True),
    sa.Column('s3_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), server_default='0', nullable=True),
    sa.Column('duration_seconds', sa.Float(precision=24), server_default='0', nullable=True),
    sa.Column('opponent', sa.Text(), server_default='', nullable=True),
    sa.Column('game_date', sa.Text(), server_default='', nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('keep_forever', sa.Integer(), server_default='0', nullable=True),
    sa.Column('source_type', sa.Text(), server_default='s3', nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scouting_videos_user_id', 'scouting_videos', ['user_id'], unique=False)
    op.create_table('session_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('topics_json', JSONText(), server_default='[]', nullable=True),
    sa.Column('agents_used_json', JSONText(), server_default='[]', nullable=True),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_session_summaries_user', 'session_summaries', ['user_id', 'team_id'], unique=False)
    op.create_table('storage_quota',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('storage_used_bytes', sa.Integer(), server_default='0', nullable=True),
    sa.Column('storage_limit_bytes', sa.BigInteger(), server_default='10737418240', nullable=True),
    sa.Column('video_ttl_days', sa.Integer(), server_default='14', nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_cache', sa.Text(), server_default='', nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uploads_team_id', 'uploads', ['team_id'], unique=False)
    op.create_index('idx_uploads_user_id', 'uploads', ['user_id'], unique=False)
    op.create_table('entity_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('source_session_id', sa.Text(), nullable=True),
    sa.Column('agent_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_obs_entity', 'entity_observations', ['entity_id'], unique=False)
    op.create_table('notebook_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='present', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['notebook_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'player_id', name='uq_nb_attendance_entry_player')
    )
    op.create_index('idx_nb_attendance_entry', 'notebook_attendance', ['entry_id'], unique=False)
    op.create_index('idx_nb_attendance_player', 'notebook_attendance', ['player_id'], unique=False)
    op.create_table('notebook_entry_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['notebook_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'player_id', name='uq_nb_entry_players_entry_player')
    )
    op.create_index('idx_nb_entry_players_player', 'notebook_entry_players', ['player_id'], unique=False)
    op.create_table('player_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('metrics_json', JSONText(), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_index('idx_player_metrics_team_id', 'player_metrics', ['team_id'], unique=False)
    op.create_index('idx_player_metrics_user_id', 'player_metrics', ['user_id'], unique=False)
    op.create_table('video_clips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Float(precision=24), nullable=False),
    sa.Column('end_time', sa.Float(precision=24), nullable=False),
    sa.Column('action_type', sa.Text(), server_default='other', nullable=True),
    sa.Column('rating', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['scouting_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=True),
    sa.Column('note', sa.Text(), server_default='', nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['video_clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['clip_playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'clip_id', name='uq_playlist_items_playlist_clip')
    )
    op.create_table('video_annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('annotation_type', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Float(precision=24), nullable=False),
    sa.Column('duration', sa.Float(precision=24), server_default='3.0', nullable=True),
    sa.Column('stroke_data', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), server_default='#FF0000', nullable=True),
    sa.Column('stroke_width', sa.Integer(), server_default='3', nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['video_clips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['scouting_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_annotations')
    op.drop_table('playlist_items')
    op.drop_table('video_clips')
    op.drop_index('idx_player_metrics_user_id', table_name='player_metrics')
    op.drop_index('idx_player_metrics_team_id', table_name='player_metrics')
    op.drop_table('player_metrics')
    op.drop_index('idx_nb_entry_players_player', table_name='notebook_entry_players')
    op.drop_table('notebook_entry_players')
    op.drop_index('idx_nb_attendance_player', table_name='notebook_attendance')
    op.drop_index('idx_nb_attendance_entry', table_name='notebook_attendance')
    op.drop_table('notebook_attendance')
    op.drop_index('idx_entity_obs_entity', table_name='entity_observations')
    op.drop_table('entity_observations')
    op.drop_index('idx_uploads_user_id', table_name='uploads')
    op.drop_index('idx_uploads_team_id', table_name='uploads')
    op.drop_table('uploads')
    op.drop_table('storage_quota')
    op.drop_index('idx_session_summaries_user', table_name='session_summaries')
    op.drop_table('session_summaries')
    op.drop_index('idx_scouting_videos_user_id', table_name='scouting_videos')
    op.drop_table('scouting_videos')
    op.drop_table('plays')
    op.drop_index('idx_players_user_id', table_name='players')
    op.drop_index('idx_players_team_id', table_name='players')
    op.drop_table('players')
    op.drop_index('idx_pgs_team_game', table_name='player_game_stats')
    op.drop_index('idx_pgs_player', table_name='player_game_stats')
    op.drop_index('idx_pgs_entry', table_name='player_game_stats')
    op.drop_table('player_game_stats')
    op.drop_index('idx_onb_user_team', table_name='onboarding_events')
    op.drop_table('onboarding_events')
    op.drop_index('idx_nb_entries_team_type', table_name='notebook_entries')
    op.drop_index('idx_nb_entries_player', table_name='notebook_entries')
    op.drop_index('idx_nb_entries_date', table_name='notebook_entries')
    op.drop_table('notebook_entries')
    op.drop_index('idx_memories_user_team', table_name='memories')
    op.drop_index('idx_memories_user_active', table_name='memories')
    op.drop_index('idx_memories_category', table_name='memories')
    op.drop_table('memories')
    op.drop_index('idx_feedback_user_agent', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('idx_entities_user_team', table_name='entities')
    op.drop_table('entities')
    op.drop_index('idx_conversations_user_id', table_name='conversations')
    op.drop_index('idx_conversations_team_id', table_name='conversations')
    op.drop_index('idx_conversations_session', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('clip_playlists')
    op.drop_index('idx_api_usage_user', table_name='api_usage_logs')
    op.drop_index('idx_api_usage_model', table_name='api_usage_logs')
    op.drop_index('idx_api_usage_date', table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    op.drop_table('team_profile')
    op.drop_index('idx_social_provider', table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_table('scouting_players')
    op.drop_table('sales_inquiries')
    op.drop_index('idx_refresh_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_push_subs_user', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index('idx_push_log_user_sent', table_name='push_log')
    op.drop_index('idx_push_log_status', table_name='push_log')
    op.drop_table('push_log')
    op.drop_table('play_shares')
    op.drop_index('idx_pv_user', table_name='page_views')
    op.drop_index('idx_pv_session', table_name='page_views')
    op.drop_index('idx_pv_section', table_name='page_views')
    op.drop_index('idx_pv_date', table_name='page_views')
    op.drop_table('page_views')
    op.drop_index('idx_mailing_list_members_user', table_name='mailing_list_members')
    op.drop_table('mailing_list_members')
    op.drop_index('idx_invite_code', table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index('idx_email_log_user_template', table_name='email_log')
    op.drop_index('idx_email_log_status_date', table_name='email_log')
    op.drop_table('email_log')
    op.drop_table('compile_cards')
    op.drop_index('idx_coach_prefs_user', table_name='coach_preferences')
    op.drop_table('coach_preferences')
    op.drop_table('clip_shares')
    op.drop_index('idx_auth_tokens_user_purpose', table_name='auth_tokens')
    op.drop_index('idx_auth_tokens_expires', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_deleted', table_name='users')
    op.drop_index('idx_users_club', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_admin_task_subtasks_task', table_name='admin_task_subtasks')
    op.drop_table('admin_task_subtasks')
    op.drop_index('idx_admin_task_comments_task', table_name='admin_task_comments')
    op.drop_table('admin_task_comments')
    op.drop_index('idx_research_url_log_used_at', table_name='research_url_log')
    op.drop_index('idx_research_url_log_tier', table_name='research_url_log')
    op.drop_index('idx_research_url_log_domain', table_name='research_url_log')
    op.drop_table('research_url_log')
    op.drop_table('mailing_lists')
    op.drop_table('ip_geo_cache')
    op.drop_table('clubs')
    op.drop_index('idx_admin_tasks_status', table_name='admin_tasks')
    op.drop_index('idx_admin_tasks_priority', table_name='admin_tasks')
    op.drop_index('idx_admin_tasks_due_date', table_name='admin_tasks')
    op.drop_table('admin_tasks')
    # ### end Alembic commands ###
