"""Alembic environment for NEXTPLAY FastAPI (async).

Reads the database URL from src.core.config.settings at runtime so it
matches the same logic as the running app (asyncpg in prod, aiosqlite in dev).

Migrations call AsyncEngine.run_sync(do_run_migrations) to bridge async
SQLAlchemy with Alembic's sync migration API.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from src.core.config import settings
from src.core.database import Base

# Import every model so Base.metadata sees all 47 tables.
# `src.models.__init__` re-exports each ORM class — pulling that one symbol
# transitively imports every model module.
from src.models import *  # noqa: F401, F403, E402


config = context.config

# Override sqlalchemy.url from settings so we never hard-code a URL.
config.set_main_option("sqlalchemy.url", settings.database_url_async)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (no connection, just emits SQL)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
        render_item=render_item,
    )

    with context.begin_transaction():
        context.run_migrations()


def render_item(type_: str, obj, autogen_context):
    """Render custom column types cleanly so autogenerated migrations are
    importable without dotted module paths.

    Without this, `JSONText` is rendered as `src.core.database.JSONText()`,
    which fails at upgrade time because the migration file has no `import src`.
    """
    if type_ == "type" and obj.__class__.__name__ == "JSONText":
        autogen_context.imports.add("from src.core.database import JSONText")
        return "JSONText()"
    return False  # let Alembic use its default rendering


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        compare_server_default=True,
        render_item=render_item,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """Run migrations in 'online' mode using the async engine."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
